# Generated by Django 5.0.7 on 2024-10-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(upload_to='coaches/'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', '星期一'), ('Tuesday', '星期二'), ('Wednesday', '星期三'), ('Thursday', '星期四'), ('Friday', '星期五'), ('Saturday', '星期六'), ('Sunday', '星期日')], max_length=10),
        ),
    ]
