# Generated by Django 5.0.7 on 2024-10-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coach_slug_coursetype_description_coursetype_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='personal_traits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='teaching_method',
            field=models.TextField(blank=True, null=True),
        ),
    ]
