# Generated by Django 5.0.7 on 2024-10-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_managers_remove_user_occupation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('grade', models.IntegerField()),
                ('motivation', models.JSONField()),
                ('techniques', models.JSONField()),
                ('coach_gender', models.CharField(blank=True, max_length=20)),
                ('coach_traits', models.JSONField()),
                ('course_type', models.JSONField()),
                ('sub_course_type', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
    ]
