# Generated by Django 5.0.7 on 2024-10-14 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coach_personal_traits_coach_teaching_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='applicable_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coach'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
