# Generated by Django 5.0.7 on 2024-10-14 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coursetype_applicable_level_coursetype_coach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetype',
            name='schedule',
        ),
    ]
