# Generated by Django 5.0.7 on 2024-10-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_coursetype_additional_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetype',
            old_name='additional_description',
            new_name='additional_description_1',
        ),
        migrations.AddField(
            model_name='coursetype',
            name='additional_description_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
