# Generated by Django 5.0.7 on 2024-10-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_additional_description_coursetype_additional_description_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetype',
            name='coach',
        ),
        migrations.AddField(
            model_name='coursetype',
            name='coaches',
            field=models.ManyToManyField(blank=True, to='app.coach'),
        ),
    ]
