# Generated by Django 5.0.7 on 2024-10-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_coursetype_coach_coursetype_coaches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseReservation',
        ),
    ]
