# Generated by Django 5.0.7 on 2024-10-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_coursereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
